<?php

use Illuminate\Database\Seeder;

class QuestionnaireQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$list = array(
    		array('jenis_survey' => '1', 'num_episode' => '3', 'num_kuis' => '1', 'kuis' => 'Apakah benar Bapak/Ibu baru-baru ini melakukan pemasangan Indihome?', 'jenis_input' => 'select', 'range' => 'Ya|Tidak', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '3', 'num_kuis' => '2', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu melakukan pemasangan Indihome, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikannya ke saudara atau rekan Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '3', 'num_kuis' => '3', 'kuis' => 'Apa alasan bapak/ibu memberikan nilai tersebut', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '4', 'num_kuis' => '1', 'kuis' => 'Apakah benar Bapak/Ibu memakai layanan Indihome?', 'jenis_input' => 'select', 'range' => 'Ya|Tidak', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '4', 'num_kuis' => '2', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu memakai layanan Indihome, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikannya ke saudara atau rekan Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '4', 'num_kuis' => '3', 'kuis' => 'Apa alasan bapak/ibu memberikan nilai tersebut?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '5', 'num_kuis' => '1', 'kuis' => 'Apakah benar Bapak/Ibu memakai layanan Internet Indihome?', 'jenis_input' => 'select', 'range' => 'Ya|Tidak', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '5', 'num_kuis' => '2', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu memakai layanan Internet Indihome, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikannya ke saudara atau rekan Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin.', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '5', 'num_kuis' => '3', 'kuis' => 'Apa alasan bapak/ibu memberikan nilai tersebut?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '6', 'num_kuis' => '1', 'kuis' => 'Apakah benar Bapak/Ibu memakai layanan TV Kabel Indihome?', 'jenis_input' => 'select', 'range' => 'Ya|Tidak', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '6', 'num_kuis' => '2', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu memakai layanan TV Kabel Indihome, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikannya ke saudara atau rekan Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin.', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '6', 'num_kuis' => '3', 'kuis' => 'Apa alasan bapak/ibu memberikan nilai tersebut?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '7', 'num_kuis' => '1', 'kuis' => 'Apakah benar Bapak/Ibu memakai layanan Telepon rumah?', 'jenis_input' => 'select', 'range' => 'Ya|Tidak', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '7', 'num_kuis' => '2', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu memakai layanan Telepon rumah, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikannya ke saudara atau rekan Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '7', 'num_kuis' => '3', 'kuis' => 'Apa alasan bapak/ibu memberikan nilai tersebut?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '10', 'num_kuis' => '1', 'kuis' => 'Apakah benar Bapak/Ibu baru-baru ini mendapat penanganan atas gangguan layanan Indihome?', 'jenis_input' => 'select', 'range' => 'Ya|Tidak', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '10', 'num_kuis' => '2', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam proses penanganan gangguan layanan Indihome, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikannya ke saudara atau rekan Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '10', 'num_kuis' => '3', 'kuis' => 'Apa alasan bapak/ibu memberikan nilai tersebut?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '11', 'num_kuis' => '1', 'kuis' => 'Apakah benar Bapak/Ibu baru-baru ini memutus layanan Indihome?', 'jenis_input' => 'select', 'range' => 'Ya|Tidak', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '11', 'num_kuis' => '2', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam memutus layanan Indihome, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikan Indihome ke saudara atau rekan Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin.', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '1', 'num_episode' => '11', 'num_kuis' => '3', 'kuis' => 'Apa alasan bapak/ibu memberikan nilai tersebut?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '3', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal aktivasi, pemasangan, atau instalasi layanan  PT Telkom Indonesia, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bpk/ Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin.', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '3', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu tersebut?', 'jenis_input' => 'select', 'range' => 'Kualitas layanan|Waktu penyelesaian|Pengaturan jadwal dengan teknisi|Kemudahan koordinasi dengan teknisi|Kecakapan Petugas Telkom |Informasi progress pemasangan layanan|Kerapihan instalasi|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '3', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '10', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal penanganan gangguan layanan  PT Telkom Indonesia, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bpk/ Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '10', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Informasi progress penanganan gangguan|Waktu penyelesaian|Pengaturan jadwal dengan teknisi|Kemudahan koordinasi dengan teknisi|Kecakapan Petugas Telkom|Kerapihan instalasi|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '10', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '9', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam pelayanan invoice atau tagihan dan pembayaran PT Telkom Indonesia, dari skala 0 sampai 10 seberapa besar kemungkinan Bapak/Ibu merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bpk/ Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '9', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Akurasi invoice|Waktu penyampaian invoice|Kemudahan koordinasi dengan petugas pembayaran|Kecakapan Petugas Telkom|Kemudahan proses pembayaran|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '9', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '4', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal penggunaan produk PT Telkom Indonesia, dari skala 0 sampai dengan 10 seberapa besar kemungkinan Bapak/Ibu untuk merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '4', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Kehandalan layanan|Kesesuaian kualitas dengan spesifikasi dengan kontrak|Ketersediaan informasi jaringan atau penggunaan layanan|Kemudahan penggunaan layanan|Kemudahan perubahan atau upgrade layanan|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '4', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '5', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal penggunaan produk PT Telkom Indonesia, dari skala 0 sampai dengan 10 seberapa besar kemungkinan Bapak/Ibu untuk merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '5', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Kehandalan layanan|Kesesuaian kualitas dengan spesifikasi dengan kontrak|Ketersediaan informasi jaringan atau penggunaan layanan|Kemudahan penggunaan layanan|Kemudahan perubahan atau upgrade layanan|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '5', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '6', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal penggunaan produk PT Telkom Indonesia, dari skala 0 sampai dengan 10 seberapa besar kemungkinan Bapak/Ibu untuk merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '6', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Kehandalan layanan|Kesesuaian kualitas dengan spesifikasi dengan kontrak|Ketersediaan informasi jaringan atau penggunaan layanan|Kemudahan penggunaan layanan|Kemudahan perubahan atau upgrade layanan|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '6', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '7', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal penggunaan produk PT Telkom Indonesia, dari skala 0 sampai dengan 10 seberapa besar kemungkinan Bapak/Ibu untuk merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '7', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Kehandalan layanan|Kesesuaian kualitas dengan spesifikasi dengan kontrak|Ketersediaan informasi jaringan atau penggunaan layanan|Kemudahan penggunaan layanan|Kemudahan perubahan atau upgrade layanan|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '7', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '8', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal penggunaan produk PT Telkom Indonesia, dari skala 0 sampai dengan 10 seberapa besar kemungkinan Bapak/Ibu untuk merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '8', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Kehandalan layanan|Kesesuaian kualitas dengan spesifikasi dengan kontrak|Ketersediaan informasi jaringan atau penggunaan layanan|Kemudahan penggunaan layanan|Kemudahan perubahan atau upgrade layanan|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '8', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '9', 'num_kuis' => '1', 'kuis' => 'Berdasarkan pengalaman Bapak/Ibu dalam hal penggunaan produk PT Telkom Indonesia, dari skala 0 sampai dengan 10 seberapa besar kemungkinan Bapak/Ibu untuk merekomendasikan layanan PT Telkom Indonesia ke rekan kerja, kolega atau mitra bisnis Bapak/Ibu? Silahkan pilih 1 angka, dimana 0 sangat tidak mungkin dan 10 sangat mungkin', 'jenis_input' => 'select', 'range' => '0|1|2|3|4|5|6|7|8|9|10', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '9', 'num_kuis' => '2', 'kuis' => 'Apa faktor yang mendasari penilaian Bpk/Ibu?', 'jenis_input' => 'select', 'range' => 'Kehandalan layanan|Kesesuaian kualitas dengan spesifikasi dengan kontrak|Ketersediaan informasi jaringan atau penggunaan layanan|Kemudahan penggunaan layanan|Kemudahan perubahan atau upgrade layanan|Lainnya', 'jenis_kuisioner' => '1'),
    		array('jenis_survey' => '2', 'num_episode' => '9', 'num_kuis' => '3', 'kuis' => 'Ada masukan untuk Telkom?', 'jenis_input' => 'textarea', 'range' => '', 'jenis_kuisioner' => '1'),
    	);
	DB::table('tr_questionnaire_question')->insert($list);
}
}
